import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Damian Falcon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <div>
          <h1
            style={{
              textAlign: "center",
            }}
          >
            COMING SOON!!!
          </h1>
          <h2>We work hard to provide you the best experience.</h2>
          {/* <hr /> */}
          <img src="/under_construction.jpg"></img>
        </div>
      </body>
    </div>
  );
}
